"""Visual assets for the RouteWise demo: the app's own logo mark, and real
model logos (via Simple Icons, CC0-licensed monochrome brand marks meant to
be recolored/embedded — used here purely for attribution, not resale).
Gemma has no dedicated Simple Icons entry, so its badge uses Google
Gemini's spark mark (same Google DeepMind lineage) with a "(Google)" label
for clarity. Kimi likewise has no dedicated entry - its badge uses Moonshot
AI's mark (Kimi's maker) with a "(Moonshot AI)" label rather than passing
off an unrelated logo as Kimi's own.
"""

# --- RouteWise's own mark: a routing "fork" - one node branching into
# several - matching webapp/favicon.png (generated by generate_favicon.py).
ROUTEWISE_LOGO_SVG = """
<svg width="40" height="40" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="rwGrad" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#A78BFA"/>
      <stop offset="55%" stop-color="#60E6D8"/>
      <stop offset="100%" stop-color="#5CC8FC"/>
    </linearGradient>
  </defs>
  <path d="M12 20 L12 14 M12 14 L5 6 M12 14 L12 5 M12 14 L19 6"
        stroke="url(#rwGrad)" stroke-width="2.1" stroke-linecap="round" fill="none"/>
  <circle cx="12" cy="20" r="2.5" fill="#C8BEFA"/>
  <circle cx="12" cy="14" r="1.6" fill="#C8BEFA"/>
  <circle cx="5" cy="6" r="2.2" fill="#A78BFA"/>
  <circle cx="12" cy="5" r="2.2" fill="#60E6D8"/>
  <circle cx="19" cy="6" r="2.2" fill="#5CC8FC"/>
</svg>
"""

# Path data straight from Simple Icons (cdn.simpleicons.org/<slug>), CC0.
_MINIMAX_PATH = (
    'M11.43 3.92a.86.86 0 1 0-1.718 0v14.236a1.999 1.999 0 0 1-3.997 0V9.022a.86.86 '
    '0 1 0-1.718 0v3.87a1.999 1.999 0 0 1-3.997 0V11.49a.57.57 0 0 1 1.139 0v1.404a.86.86 '
    '0 0 0 1.719 0V9.022a1.999 1.999 0 0 1 3.997 0v9.134a.86.86 0 0 0 1.719 0V3.92a1.998 1.998 '
    '0 1 1 3.996 0v11.788a.57.57 0 1 1-1.139 0zm10.572 3.105a2 2 0 0 0-1.999 1.997v7.63a.86.86 '
    '0 0 1-1.718 0V3.923a1.999 1.999 0 0 0-3.997 0v16.16a.86.86 0 0 1-1.719 0V18.08a.57.57 0 '
    '1 0-1.138 0v2a1.998 1.998 0 0 0 3.996 0V3.92a.86.86 0 0 1 1.719 0v12.73a1.999 1.999 0 '
    '0 0 3.996 0V9.023a.86.86 0 1 1 1.72 0v6.686a.57.57 0 0 0 1.138 0V9.022a2 2 0 0 0-1.998-1.997'
)
_MOONSHOT_PATH = (
    'm1.053 16.91 9.538 2.55a21 20.981 0 0 0 .06 2.031l5.956 1.592a12 11.99 0 0 1-15.554-6.172'
    'm-1.02-5.79 11.352 3.035a21 20.981 0 0 0-.469 2.01l10.817 2.89a12 11.99 0 0 1-1.845 '
    '2.004L.658 15.918a12 11.99 0 0 1-.625-4.796m1.593-5.146L13.573 9.17a21 20.981 0 0 '
    '0-1.01 1.874l11.297 3.02a21 20.981 0 0 1-.67 2.362l-11.55-3.087L.125 10.26a12 11.99 '
    '0 0 1 1.499-4.285ZM6.067 1.58l11.285 3.016a21 20.981 0 0 0-1.688 1.719l7.824 2.091a21 '
    '20.981 0 0 1 .513 2.664L2.107 5.218a12 11.99 0 0 1 3.96-3.638M21.68 4.866 7.222 1.003A12 '
    '11.99 0 0 1 21.68 4.866'
)
_GEMINI_PATH = (
    'M11.04 19.32Q12 21.51 12 24q0-2.49.93-4.68.96-2.19 2.58-3.81t3.81-2.55Q21.51 12 24 12q-2.49 '
    '0-4.68-.93a12.3 12.3 0 0 1-3.81-2.58 12.3 12.3 0 0 1-2.58-3.81Q12 2.49 12 0q0 2.49-.96 '
    '4.68-.93 2.19-2.55 3.81a12.3 12.3 0 0 1-3.81 2.58Q2.49 12 0 12q2.49 0 4.68.96 2.19.93 '
    '3.81 2.55t2.55 3.81'
)
_QWEN_PATH = (
    'M23.919 14.545 20.817 9.17l1.47-2.544a.56.56 0 0 0 0-.566l-1.633-2.83a.57.57 0 0 0-.49-.283'
    'h-6.207L12.487.402a.57.57 0 0 0-.49-.284H8.732a.56.56 0 0 0-.49.284L5.139 5.775h-2.94a.56.56 '
    '0 0 0-.49.284L.077 8.887a.56.56 0 0 0 0 .567L3.18 14.83l-1.47 2.545a.56.56 0 0 0 0 .566l1.634 '
    '2.83a.57.57 0 0 0 .49.283h6.205l1.47 2.545a.57.57 0 0 0 .49.284h3.266a.57.57 0 0 0 '
    '.49-.284l3.104-5.375h2.94a.57.57 0 0 0 .49-.283l1.634-2.828a.55.55 0 0 0-.004-.568M8.733.686'
    'l1.634 2.828-1.634 2.828H21.8L20.164 9.17H7.425L5.63 6.06Zm1.306 19.801-6.205-.002 1.634-2.83'
    'h3.265L2.201 6.344h3.267q3.182 5.517 6.367 11.032zm10.124-5.66L18.53 12l-6.532 11.315-1.634-2.83'
    'c2.129-3.673 4.25-7.351 6.373-11.028h3.592l3.102 5.374z'
)


def _mini_svg(path: str, fill: str, size: int = 14) -> str:
    return (
        f'<svg width="{size}" height="{size}" viewBox="0 0 24 24" '
        f'xmlns="http://www.w3.org/2000/svg"><path fill="{fill}" d="{path}"/></svg>'
    )


# hint -> (display name, badge HTML, background)
# Real logos sit on a small white chip for consistent contrast/authenticity
# regardless of each brand's own fill color. "Local" has no real brand, so
# it gets a distinct custom bolt icon on a colored chip instead - visually
# signaling "this one's ours, not a hosted model."
_BOLT_SVG = _mini_svg(
    "M13 2 3 14h7l-1 8 10-12h-7z", "#0E1117", size=13
)

MODEL_BADGES = [
    ("minimax", "MiniMax M3", _mini_svg(_MINIMAX_PATH, "#E73562"), "#FFFFFF"),
    ("kimi", "Kimi (Moonshot AI)", _mini_svg(_MOONSHOT_PATH, "#111111"), "#FFFFFF"),
    ("gemma", "Gemma (Google)", _mini_svg(_GEMINI_PATH, "#8E75B2"), "#FFFFFF"),
    ("qwen-coder", "Qwen2.5-Coder-1.5B", _mini_svg(_QWEN_PATH, "#6950EF"), "#FFFFFF"),
    ("qwen", "Qwen2.5-1.5B", _mini_svg(_QWEN_PATH, "#6950EF"), "#FFFFFF"),
    ("local", "Local (0 tokens)", _BOLT_SVG, "linear-gradient(135deg,#43E97B,#38F9D7)"),
]

# The two GGUF models actually bundled in the submitted Docker image
# (router/local_llm.py) - shown as a static reference section since this
# hosted demo doesn't run them itself (see the caption in app.py).
LOCAL_MODELS = [
    ("qwen", "Qwen2.5-1.5B-Instruct", "factual, sentiment, NER, summarisation"),
    ("qwen-coder", "Qwen2.5-Coder-1.5B-Instruct", "code_debug, code_gen"),
]
